global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
# Prometheus self-monitoring
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]
    labels:
      service: 'prometheus'
      environment: 'production'

# Traefik metrics
- job_name: 'traefik'
  scrape_interval: 10s
  static_configs:
  - targets: [ 'traefik:8082' ]
    labels:
      service: 'traefik'
      environment: 'production'
  metrics_path: /metrics

# Redis metrics (redis_exporter)
- job_name: 'redis'
  static_configs:
  - targets: [ 'redis:6379' ]
    labels:
      service: 'redis'
      environment: 'production'
  scrape_interval: 30s

# MongoDB metrics (mongodb_exporter)
- job_name: 'mongodb'
  static_configs:
  - targets: [ 'mongodb:27017' ]
    labels:
      service: 'mongodb'
      environment: 'production'
  scrape_interval: 30s

# API Backend metrics (custom endpoint /metrics si se implementa)
- job_name: 'api-backend'
  static_configs:
  - targets: [ 'api-backend:3000' ]
    labels:
      service: 'image-express-api'
      component: 'backend'
      environment: 'production'
  metrics_path: /metrics
  scrape_interval: 15s

# Worker metrics (custom endpoint /metrics)
- job_name: 'image-worker'
  static_configs:
  - targets: [ 'worker:3001' ]
    labels:
      service: 'image-processing-worker'
      component: 'worker'
      environment: 'production'
  metrics_path: /metrics
  scrape_interval: 15s

# Alerting rules (opcional)
alerting:
  alertmanagers:
  - static_configs:
    - targets:
        # - alertmanager:9093

        # Remote write/read (para almacenamiento externo)
        # remote_write:
        #   - url: "https://prometheus-remote-write-endpoint"
        #     basic_auth:
        #       username: user
        #       password: pass
