apiVersion: 1

datasources:
# Loki for logs
- name: Loki
  type: loki
  uid: loki-ds
  access: proxy
  url: http://loki:3100
  isDefault: false
  editable: false
  jsonData:
    maxLines: 1000
    derivedFields:
    - datasourceUid: prometheus-ds
      matcherRegex: "taskId=([\\w-]+)"
      name: "Task ID"
      url: "/d/image-api-dashboard/image-processing-api?var-task_id=$${__value.raw}"
  version: 1

# Prometheus for metrics
- name: Prometheus
  type: prometheus
  uid: prometheus-ds
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: false
  jsonData:
    timeInterval: "15s"
    queryTimeout: "60s"
    httpMethod: POST
  version: 1

# Redis datasource for queue monitoring
- name: Redis
  type: redis-datasource
  uid: redis-ds
  access: proxy
  url: redis://redis:6379
  isDefault: false
  editable: false
  jsonData:
    client: "standalone"
    poolSize: 5
    timeout: 10
    pingInterval: 0
    pipelineWindow: 0
  secureJsonData:
    password: ${REDIS_PASSWORD}
  version: 1
